#!/usr/bin/env node
// Regenerate bench/results/REPORT.md from the committed result JSONs.
// Never hand-edit the report — rerun the benches, then this.
'use strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const res = (f) => JSON.parse(fs.readFileSync(path.join(here, 'results', f), 'utf8'));
const gate = res('gate.json');
const fp = res('footprint.json');
const compress = res('compress.json');
const live2 = res('live2.json');
let agentic = null;
try { agentic = res('agentic.json'); } catch {}

// Cluster bootstrap over tasks: resample the 14 tasks with replacement, pool
// off/on token means, 2000 reps -> percentile 95% CI on the savings figure.
function bootstrapCI(rows, offKey, onKey, reps = 2000) {
  const stats = [];
  for (let i = 0; i < reps; i++) {
    let off = 0, on = 0;
    for (let k = 0; k < rows.length; k++) {
      const r = rows[Math.floor(Math.random() * rows.length)];
      off += r.off[offKey]; on += r.on[onKey];
    }
    stats.push(1 - on / off);
  }
  stats.sort((a, b) => a - b);
  return { lo: stats[Math.floor(0.025 * reps)], hi: stats[Math.floor(0.975 * reps)] };
}
const tokCI = bootstrapCI(live2.rows, 'tok', 'tok');

const pc = (x) => `${(x * 100).toFixed(1)}%`;
const pc0 = (x) => `${(x * 100).toFixed(0)}%`;
const saved = (off, on) => pc0(1 - on / off);

const tierRow = (name, t) =>
  `| ${name} | ${t.n} | ${t.offTok.toFixed(0)} → ${t.onTok.toFixed(0)} | ${saved(t.offTok, t.onTok)} | ${t.offLoc.toFixed(0)} → ${t.onLoc.toFixed(0)} | ${saved(t.offLoc, t.onLoc)} | ${pc0(t.offPass)} / ${pc0(t.onPass)} | ${(t.offMs / 1000).toFixed(1)}s → ${(t.onMs / 1000).toFixed(1)}s |`;

const taskRows = live2.rows.map((r) =>
  `| ${r.id} | ${r.tier} | ${r.off.tok.toFixed(0)} → ${r.on.tok.toFixed(0)} | ${saved(r.off.tok, r.on.tok)} | ${r.off.loc.toFixed(1)} → ${r.on.loc.toFixed(1)} | ${pc0(r.off.passRate)} / ${pc0(r.on.passRate)} |`).join('\n');

const md = `# Shaman benchmark report

Generated by \`node bench/report.mjs\` from \`bench/results/*.json\`. Regenerate, never edit.

## 1. Prompt gate — ${gate.prompts} labeled prompts (EN+PT), deterministic

| metric | result |
|---|---|
| vague prompts caught | **${pc(gate.vagueRecall)}** (all hard-blocked in coach mode) |
| underspecified enriched (incl. verbose-vague) | **${pc(gate.mediumCaught)}** |
| strong passed silently (incl. complex multi-requirement briefs) | **${pc(gate.strongSilent)}** |
| false blocks on legitimate prompts | **${gate.falseBlocks}** |
| latency per prompt (end-to-end, incl. node boot) | ${gate.latencyMeanMs.toFixed(0)} ms mean |

Complex multi-requirement briefs (rate limiting with headers + isolation, zero-downtime
UUID migration, race-condition fix with SKIP LOCKED...) all pass silently; verbose-but-vague
prompts ("refactor everything to be modern...") are all caught — word count alone never
buys a silent pass. This suite runs in CI; one false block fails the build.

## 2. Ruleset footprint

| mode | tokens (cl100k proxy) |
|---|---|
| full | ${fp.rules.full.tokens} |
| lite | ${fp.rules.lite.tokens} |
| ultra | ${fp.rules.ultra.tokens} |
| off | 0 |

Injected once per session (and per subagent), not per turn.

## 3. Talk economy — matched-content pairs

**${pc(compress.pooledSaved)}** fewer output tokens (${compress.sumDef} → ${compress.sumSha}) across ${Array.isArray(compress.pairs) ? compress.pairs.length : compress.pairs} pairs holding facts, code, and numbers constant. Measures the style, not a live workload.

## 4. Live A/B v2 — tiered, correctness-gated (${live2.model}, ${live2.trials} trials/arm)

Both arms get the identical prompt with an explicit export contract. Generated code is
executed against adversarial asserts (\`bench/checks.mjs\`); a smaller answer that fails
its gate is a loss, not a saving.

| tier | tasks | output tokens | saved | LOC | saved | correctness off/on | time |
|---|---|---|---|---|---|---|---|
${tierRow('small', live2.tiers.small)}
${tierRow('medium', live2.tiers.medium)}
${tierRow('large', live2.tiers.large)}
| **all** | ${live2.overall.n} | ${live2.overall.offTok.toFixed(0)} → ${live2.overall.onTok.toFixed(0)} | **${saved(live2.overall.offTok, live2.overall.onTok)}** | ${live2.overall.offLoc.toFixed(0)} → ${live2.overall.onLoc.toFixed(0)} | **${saved(live2.overall.offLoc, live2.overall.onLoc)}** | ${pc0(live2.overall.offPass)} / ${pc0(live2.overall.onPass)} | ${(live2.overall.offMs / 1000).toFixed(1)}s → ${(live2.overall.onMs / 1000).toFixed(1)}s |

Comment lines: ${live2.overall.offComments.toFixed(0)} → ${live2.overall.onComments.toFixed(0)}. Run cost: $${live2.costUsd.toFixed(2)}.
Pooled token savings 95% CI (task-cluster bootstrap, 2000 reps): **[${pc0(tokCI.lo)}, ${pc0(tokCI.hi)}]**.

### Per task

| task | tier | tokens | saved | LOC | pass off/on |
|---|---|---|---|---|---|
${taskRows}

${agentic ? `## 5. Agentic — real multi-turn sessions with tools (${agentic.model}, ${agentic.trials} trials/arm)

Six real tickets against the pinned fixture app (\`bench/fixtures/notes-api\`): sessions run
with read/edit/bash tools in an isolated workspace (\`--setting-sources project,local\`, own
git repo, budget-capped). "Done" = fixture test suite green AND the ticket's black-box
acceptance check passes (checks proven to fail on the pristine fixture, in CI).

| metric | off | on | delta |
|---|---|---|---|
| completion | ${pc0(agentic.off.done)} | ${pc0(agentic.on.done)} | ${agentic.on.done >= agentic.off.done ? 'held or improved' : 'REGRESSED'} |
| session cost (sum) | $${agentic.off.cost.toFixed(3)} | $${agentic.on.cost.toFixed(3)} | ${saved(agentic.off.cost, agentic.on.cost)} saved |
| output tokens (sum) | ${agentic.off.output.toFixed(0)} | ${agentic.on.output.toFixed(0)} | ${saved(agentic.off.output, agentic.on.output)} |
| total in+out+cache-write | ${agentic.off.total.toFixed(0)} | ${agentic.on.total.toFixed(0)} | ${saved(agentic.off.total, agentic.on.total)} |
| cache reads (sum) | ${agentic.off.cacheRead.toFixed(0)} | ${agentic.on.cacheRead.toFixed(0)} | ${saved(agentic.off.cacheRead, agentic.on.cacheRead)} |
| diff size (sum) | +${agentic.off.added.toFixed(0)} loc | +${agentic.on.added.toFixed(0)} loc | ${saved(agentic.off.added, agentic.on.added)} |
| mean session time | ${(agentic.off.ms / 1000).toFixed(0)}s | ${(agentic.on.ms / 1000).toFixed(0)}s | — |

| ticket | done off/on | cost off/on | out tok off/on | +loc off/on |
|---|---|---|---|---|
${agentic.rows.map((r) => `| ${r.id} | ${pc0(r.off.done)}/${pc0(r.on.done)} | $${r.off.cost.toFixed(3)}/$${r.on.cost.toFixed(3)} | ${r.off.output.toFixed(0)}/${r.on.output.toFixed(0)} | ${r.off.added.toFixed(0)}/${r.on.added.toFixed(0)} |`).join('\n')}

Bench spend: $${agentic.spendUsd.toFixed(2)}.

` : ''}## Honest limits

- One model (${live2.model}), ${live2.trials} trials/arm — directional, not a guarantee. Model output is high-variance; rerun for your own numbers.
- Correctness gates are a floor (deterministic asserts on stated contracts), not proof of general quality.
- Token counts in sections 2–3 use cl100k as a proxy for Claude's non-public tokenizer (±10-15%).
- The gate corpus is hand-labeled by us; extend \`corpus/prompts.jsonl\` and rerun.
- Per-session numbers from your real usage: \`/shaman-bench\`. \`/usage\` is the source of truth.
`;

fs.writeFileSync(path.join(here, 'results', 'REPORT.md'), md);
console.log('wrote bench/results/REPORT.md');
